apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryvwg5821.azurecr.io/tripviewer:1.0
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: "http://userprofile"
          - name: TRIPS_API_ENDPOINT
            value: "http://trips"
---

apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: tripviewer1
spec:
 selector:
   # Selector for Pods
   app: tripviewer
 ports:
   # Port Map
 - port: 80
   targetPort: 80
   protocol: TCP
 type: LoadBalancer
